services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propertyhub-web
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - localstack
      - redis
    entrypoint: >
      sh -c "
        uv run python manage.py migrate &&
        uv run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3 --timeout=120
      "

  db:
    image: postgres:17
    container_name: propertyhub-db
    restart: always
    environment:
      POSTGRES_USER: propertyhub
      POSTGRES_PASSWORD: propertyhub
      POSTGRES_DB: propertyhub
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: propertyhub-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=prod
      - AWS_SECRET_ACCESS_KEY=prod
  
  redis:
    image: redis:7
    container_name: propertyhub-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  redis-data:
