[project]
name = "property-hub"
version = "0.1.0"
description = "Django Property Management System"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "pillow>=11.2.1",
    "gunicorn>=23.0.0",
    "whitenoise>=6.9.0",
    "django-storages>=1.14.6",
    "boto3>=1.38.35",
    "django-extensions>=4.1",
    "django-axes>=8.0.0",
    "psycopg[binary]>=3.2.10",
    "werkzeug>=3.1.3",
    "environs[django]>=14.5.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=5.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["config", "apps", "templates"]
